function [BW,maskedImage] = segmentImage(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 14-Aug-2024
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% 图割
foregroundInd = [36803 36804 36805 36806 36807 38798 38799 38801 38802 38803 40961 40962 42411 42961 46411 46589 46960 46961 48411 48588 48589 48958 48960 50411 50575 50576 50577 50579 50580 50581 50582 50583 50584 50585 50586 50588 50957 50958 52411 52572 52573 52957 54411 54566 54567 54568 54570 54571 54955 54956 56411 56953 56954 56955 58952 58953 60952 ];
backgroundInd = [4569 4570 4571 4572 6577 8577 48339 50339 54501 ];
L = superpixels(X,800);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

